### ISSUE TITLE
"Apply matching rules using the first element of the spec array"

### ISSUE THREAD

**Issue by zhammer** [reecetech/pactman#11]
https://github.com/reecetech/pactman/blob/7cb23a46c2af6387d3297205a6a7c40b30afbff3/pactman/verifier/verify.py#L325

Out of curiosity: is this behavior part of the pact specification?

It seems odd to me that I wouldn't be able to verify the pact:

provider: `AlphabetService`
upon_receiving: `/alphabet?limit=3`
responds_with: `'letters': ['a', 'b', 'c']`
matching_rules: None

with the response: `'letters': ['a', 'b', 'c']`, since each `data_elem` will be compared not with its corresponding `spec_elem`, but with the first element in the spec. (i'll get the error `data[1] 'b' does not equal spec 'a'`.

i could understand if the idea is that expecting an exact array from a provider is too fragile and we should only look for general list matches, but just want to confirm!

**Comment by richard-reece** [comment]
Is this an actual issue you've run into? I just created a new test case based on what you've written above, and the current code passes the test case. For your reference, the test case I wrote is:

```
{
  "match": true,
  "comment": "empty arrays match",
  "expected": {
    "headers": {"Content-Type": "application/json"},
    "body": {
      "letters": ["a", "b", "c"]
    }
  },
  "actual": {
    "headers": {
      "Content-Type": "application/json"
    },
    "body": {
      "letters": ["a", "b", "c"]
    }
  }
}

```

**Comment by richard-reece** [comment]
There are specific test cases in the pact specification that relate to this:

testcases/response/body/array in different order.json (specifies that each element is tested when running an equality match)

testcases/response/body/array with type matcher.json (specifies only one element in the expected body, this only one element's type can be applied to all elements in the actual)

**Comment by zhammer** [comment]
here's the case i'm failing on.

```json
{
  "match": false,
  "comment": "empty arrays match",
  "expected": {
    "headers": {"Content-Type": "application/json"},
    "body": {
      "items": [
        {
          "id": "4",
          "song_id": "a song id",
          "song_provider": "SPOTIFY",
          "listener_name": "Farrah",
          "listen_time_utc": "2018-12-06T13:30:00",
          "iana_timezone": "America/New_York",
          "note": "I like this song!"
        },
        {
          "id": "3",
          "song_id": "a song id",
          "song_provider": "SPOTIFY",
          "listener_name": "Dorothy",
          "listen_time_utc": "2018-12-06T12:30:00",
          "iana_timezone": "America/New_York",
          "note": "I like this song!"
        }
      ]
    },
    "matchingRules": {
      "body": {
        "$.items[0].id": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[0].song_id": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[0].song_provider": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[0].iana_timezone": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[0].note": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[1].id": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[1].song_id": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[1].song_provider": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[1].iana_timezone": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        },
        "$.items[1].note": {
          "matchers": [
            {
              "match": "type"
            }
          ]
        }
      }
    }
  },
  "actual": {
    "headers": {
      "Content-Type": "application/json"
    },
    "body": {
      "items": [
        {
          "id": "4",
          "song_id": "3DnZfpfe8wLeJgzc00gKeW",
          "song_provider": "SPOTIFY",
          "listener_name": "Farrah",
          "listen_time_utc": "2018-12-06T13:30:00",
          "note": "this album isnt bad",
          "iana_timezone": "Europe/Moscow"
        },
        {
          "id": "3",
          "song_id": "3DnZfpfe8wLeJgzc00gKeW",
          "song_provider": "SPOTIFY",
          "listener_name": "Dorothy",
          "listen_time_utc": "2018-12-06T12:30:00",
          "note": "this album isnt bad",
          "iana_timezone": "Europe/Moscow"
        }
      ]
    }
  }
}
```

**Comment by zhammer** [comment]
okay, i *think* i found the issue. the `test_verifier` test cases use `success = not bool(rv.result.fail.call_count)` to determine whether or not verification is successful. they don't use the actual `rv.verify` return value. this means that if a certain failure path forgets to call `self.result.fail`, the test function will think verification was successful even though some failure was hit.

#### reproduce
here's our response body test json. i'm too tired to remember why adding the matching rule gets us into the `apply_rules_array` function but that's where the bug happens.
```json
{
  "match": true,
  "comment": "identical lists match",
  "expected": {
    "headers": {"Content-Type": "application/json"},
    "body": {
      "letters": ["a", "b", "c"]
    },
    "matchingRules": {
      "body": {
        "$.letters[2]": {"matchers": [{"match": "type"}]}
      }
    }

  },
  "actual": {
    "headers": {
      "Content-Type": "application/json"
    },
    "body": {
      "letters": ["a", "b", "c"]
    }
  }
}

```

running the tests as is should pass. *but*, if you change:
https://github.com/reecetech/pactman/blob/7cb23a46c2af6387d3297205a6a7c40b30afbff3/pactman/verifier/verify.py#L330
to
```py
return self.result.fail('oops')
```

the test case for this test should fail.

what's happening is, on the second iteration of the `for i, data_elem in enumerate(data):`, `data_elem` is 'b', but `spec_elem` is still 'a' (since we're always comparing against the first item in the spec). we eventually get to:
https://github.com/reecetech/pactman/blob/7cb23a46c2af6387d3297205a6a7c40b30afbff3/pactman/verifier/verify.py#L221
which should fail verification, but the calling function only returns `False` and `self.result.fail` is never called.


#### note
maybe there is a reason that the test cases are okay with `verify` returning `False` as long as `self.result.fail` is never called? if so, i may be wrong on this, but it seems odd to me.

**Comment by zhammer** [comment]
this is where having the matching rule present sends us down the `apply_rules` path:
https://github.com/reecetech/pactman/blob/7cb23a46c2af6387d3297205a6a7c40b30afbff3/pactman/verifier/verify.py#L188-L190

**Comment by zhammer** [comment]
also can be done more simply with:
```json
{
  "match": true,
  "comment": "identical lists match",
  "expected": {
    "headers": {"Content-Type": "application/json"},
    "body": ["a", "b", "c"],
    "matchingRules": {
      "body": {
        "$[2]": {"matchers": [{"match": "type"}]}
      }
    }

  },
  "actual": {
    "headers": {
      "Content-Type": "application/json"
    },
    "body": ["a", "b", "c"]
  }
}
```

**Comment by richard-reece** [comment]
Thank you so much for the investigation! I'll get a patch out asap.

**Comment by richard-reece** [comment]
In general there shouldn't be a failure without a `result.fail()` call (because a failure without an error message is super unhelpful). I might need to rethink how failures work.

**Comment by zhammer** [comment]
no problem! stepping through new code bases is always a fun adventure, ha.

i'm curious to see your patch for this. unfortunately (or fortunately?) i believe this uncovers a few other false positive tests in the test suite against the pact specification cases. i experimented with some simple fixes to patch the bug in my free time but realized it was quite difficult.

**Comment by richard-reece** [comment]
I've added a test to the json testcases code to check that there's a fail() called for each time it's actually failed. That's turned up a few places which I'll look at addressing, yep.

**Comment by richard-reece** [comment]
@zhammer please give that branch a try and let me know whether it addresses your issue

**Comment by zhammer** [comment]
my pact verifies now!

**Comment by richard-reece** [comment]
Excellent!
