### ISSUE TITLE
Enforce query param values are lists

### ISSUE THREAD

**Issue by richard-reece** [reecetech/pactman#25]
parse_qs and the like assume that URL query param values are lists of values. We should validate the input from Python code in case someone does `.with_request({'foo': 'bar'})`. Either we "fix" the value opaquely (which could cause user confusion) or we raise a `ValueError` from that input.

**Comment by cxong** [comment]
I think the value should be fixed opaquely. Following [`requests` library's interface](http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls), parameter values should allow both plain values and list of values.

```python
>>> payload = {'key1': 'value1', 'key2': ['value2', 'value3']}

>>> r = requests.get('https://httpbin.org/get', params=payload)
>>> print(r.url)
https://httpbin.org/get?key1=value1&key2=value2&key2=value3
```
