### ISSUE TITLE
Missing mock functionalities

### ISSUE THREAD

**Issue by ssatia** [reecetech/pactman#38]
I am new to contract testing and Pact, and am trying it out for a couple of projects that are currently mocking out interactions to one another. Ideally, I would like to use the Pact mock service in existing unit tests on the consumers for the external service calls and generate the relevant Pact files as a result. However, I have been unable to find some functionalities similar to the ones available in `unittest.mock`. Examples of this would include low-level access to the actual requests/results received by the mocking service and convenience functions like `assert_not_called`. I have been able to achieve some of these functionalities by accessing `pact._mock_handler.results`, but I would prefer not accessing private members and manipulating a `multiprocessing.Queue` to get the results.

I was wondering if this is even there is an easier way to achieve this functionality, what the analogue would be if we were not using the mock service, if this is something that we can consider adding to the project, or even if this is something we should be doing with Pacts.

**Comment by richard-reece** [comment]
Welcome!

Pact mocking isn't intended to be a general purpose mocking solution, it's really more about mocking the interface to a provider. If you need to mock and `assert_not_called()` then I recommend you just use the standard library `unittest.mock` in that situation. We absolutely do mix both styles of mocking in our tests.

**Comment by richard-reece** [comment]
BTW if you'd like some additional help with getting started with Pact and you're able to, please jump on the Pact Foundation slack: pact-foundation.slack.com
