### ISSUE TITLE
Only the last interaction's result is published to broker

### ISSUE THREAD

**Issue by RobbieClarken** [reecetech/pactman#4]
When we run `pactman-verifier`, only the result of the last interaction in the pact is published to the broker. So if the last interaction succeeds it will show green in the broker even if an earlier interaction failed.

The problem is due to the `main` function creating [a single instance of `CaptureResult`](https://github.com/reecetech/pactman/blob/master/pactman/verifier/command_line.py#L117) which is shared between the `BrokerPact` and each `Interaction`.

When each interaction is verified it will update `result.success`, overriding the value set by the previous interaction. When `BrokerPact` goes to publish the results, [it only uses the most recent `result.success`](https://github.com/reecetech/pactman/blob/master/pactman/verifier/broker_pact.py#L75-L76).

I think the solution is to create a unique result instance for each `Interaction` and have `BrokerPact` determine the aggregate result with `all(interaction.result.success for interaction in self.interactions)`.

The challenge is we need to specify some configuration for the `CaptureResult` inside `main`. I propose changing the signatures of `BrokerPacts`, `BrokerPact` and `Interaction` to accept `result_factory` instead of `result` and then we can pass `partial(CaptureResult, level=result_level)` in from `main`. Each `Interaction` class can then use `result_factory` to create its own result instance and this result will only be used for that `Interaction`.

Let me know if this sounds sane and I'll put in a PR.

**Comment by richard-reece** [comment]
SGTM! Go for it, thanks!
