### ISSUE TITLE
Disallow min: 0 for array like

### ISSUE THREAD

**Issue by bethesque** [reecetech/pactman#55]
https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes

> The same goes for specifying an array with length 0 or more. If all your provider verification data returned 0 length arrays, all your verification tests would pass without you ever having validated the contents of the array. This is why you can only specify an array with minimum length 1 OR a zero length array.

**Comment by richard-reece** [comment]
~Thanks, @bethesque, I'll amend the code.~ As far as I can tell, pactman does not allow `EachLike(minimum=0)` but I'm trying to investigate how the pact in question at https://github.com/pact-foundation/pact_broker/issues/265 was generated.

Could the pact specification be updated to include that restriction please?

**Comment by richard-reece** [comment]
Not a bug in pactman, the pact in question was generated by pact-jvm.
