### ISSUE TITLE
Please support bearer token authorization

### ISSUE THREAD

**Issue by bethesque** [reecetech/pactman#59]
Hi Richard,

Pactflow now supports authenticating with a bearer token (`Authorization: Bearer TOKEN` header). Could you add this as an option to pactman? Let me know if you have any questions.

Thanks!

**Comment by bethesque** [comment]
PS. There will be a new endpoint for fetching pacts to verify soon, to support the "pending pacts" workflow. Will send out more info when it's finished it's beta testing. The idea will be that you can run a pact verification without it failing the build, so that new contracts don't break the provider CI. It's going to be awesome!

**Comment by richard-reece** [comment]
@bethesque just to clarify, all I need to do is include the `Authorization: Bearer TOKEN` header in all requests to the pact broker, where the TOKEN is just a string provided by the user?

The other thing sounds cool :)

**Comment by bethesque** [comment]
Yes. And yes!

**Comment by bethesque** [comment]
Thanks!
