### ISSUE TITLE
PactRequestHandler.write_pact method ignores version specified

### ISSUE THREAD

**Issue by panjacek** [reecetech/pactman#7]
1. It does not check if directory exists, only for full path to file, then it tries to save without attempt to create directory. Therefore generation of pacts is crashing when there is no directory present.
2. Method does not use config.version, it has it hard-coded:
`metadata=dict(pactSpecification=dict(version='3.0.0')),`
3. It writes consumer and provider in version 2 only - as string, not as dict as specified in v3:
`pact = dict(
consumer=config.consumer_name,
provider=config.provider_name,
`
as a result verification fails due to format mismatch:
Traceback (most recent call last):
  File "/home/XXXX/.local/bin/pactman-verifier", line 11, in <module>
    load_entry_point('pactman==2.1.0', 'console_scripts', 'pactman-verifier')()
  File "/home/XXXX/.local/lib/python3.6/site-packages/pactman/verifier/command_line.py", line 131, in main
    pacts = [BrokerPact.load_file(args.local_pact_file, result_factory)]
  File "/home/XXXX/.local/lib/python3.6/site-packages/pactman/verifier/broker_pact.py", line 81, in load_file
    return cls(json.load(file), result_factory)
  File "/home/XXXX/.local/lib/python3.6/site-packages/pactman/verifier/broker_pact.py", line 57, in __init__
    self.provider = pact['provider']['name']
TypeError: string indices must be integers

**Comment by richard-reece** [comment]
Thanks for the bug report! In the future, separate bug reports with more more detail would be appreciated (for example, a traceback for the failure in #1).

For the first case, I think it would be best to throw an error if the destination directory does not exist, rather than create potentially many levels of directory in error. I'll add an explicit check for that directory.

For the second case, I will investigate the ramifications, but it will hopefully be a simple fix.

I'm confused by what you're saying in the third case, I'll have to dig deeper to understand what you're referring to.

**Comment by panjacek** [comment]
I've added small test for that class and correct version is now used (as given to config).
In terms of point 1. perhaps your suggestion is fine

That should fix point, but still point 3 is wrong.
https://github.com/panjacek/pactman/commit/577f6ab8238968a6bbb86c138cff4074f10d0848


For point 3, this should be format of v3
`{
    "consumer": {
        "name": "Consumer"
    },
    "provider": {
        "name": "Provider"
    },
`
I am confused myself now, because it looks in spec that v2 is same as dict, where pactman stores it as in Config class
`
class Config:
    def __init__(self, consumer_name, provider_name, log_dir, pact_dir, file_write_mode, version):
        self.consumer_name = consumer_name
self.provider_name = provider_name
`
then in PactRequestHandler same string is written to json as string, not dict.
consumer=config.consumer_name,
provider=config.provider_name,

**Comment by richard-reece** [comment]
I have some work in progress code to address these issues, just need to triple check the correctness of the pacts being generated. Thanks for your info and patch, it's really helped!
