### ISSUE TITLE
Add notice about being unmaintained

### ISSUE THREAD

**Issue by bethesque** [reecetech/pactman#89]
Hi,

This repository currently does not have a maintainer. Can a notice to this effect be added so that people can make an informed decision when using it?

Thanks!

**Comment by r1chardj0n3s** [comment]
This repository does have maintainers. There's just not a lot to do in maintenance mode at the moment. No new feature functionality is being worked on at present though.

**Comment by bethesque** [comment]
There are some new features coming out in the other implementations that people are going to be keen to have in Pactman. Are you likely to be able to pick them up @r1chardj0n3s?

http://blog.pact.io/2020/02/24/how-we-have-fixed-the-biggest-problem-with-the-pact-workflow/
http://blog.pact.io/2020/02/24/introducing-wip-pacts/

**Comment by r1chardj0n3s** [comment]
It's unlikely that I will find time to implement those things since I have no current need for this tool. That may change in the future. In the interim, I am (eventually) addressing bugs and other issues as they come in to keep the project active.

**Comment by bethesque** [comment]
It would be helpful to put a notice at the top that you're only fixing bugs and not adding new features then, so people can make an informed choice as to which implementation they'd like to use.
