### ISSUE TITLE
Strict matches support?

### ISSUE THREAD

**Issue by maximvl** [reecetech/pactman#98]
Hi, I wanted to ask your opinion on supporting strict matching, eg only fields declared in contract should be present and no other fields are allowed. I know it's not a part of specification, but I guess it can be added as a separate option. My use case is support for privacy/security sensitive checks. What do you think?

**Comment by r1chardj0n3s** [comment]
This does go against the intent of pact design, it'd be worth raising with the pact foundation, perhaps on their Slack: https://docs.pact.io/help/how_to_ask_for_help
